## 端口号
server:
  port: 8004


## 微服务名
spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://59.215.223.63:3306/db_bj_tj?user=root&password=@WSX3edc456&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    #url: jdbc:mysql://localhost:3306/db_bj_tj?user=root&password=root&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: '@WSX3edc456'
    #password: root
    druid:
      validation-query: SELECT 1
      test-while-idle: true
  cloud:
    zookeeper:
      connect-string: 172.16.6.202:2181
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

