## 端口号
server:
  port: 8001

## 微服务名
spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://59.215.223.63:3306/db_bj_tj?user=root&password=@WSX3edc456&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    #url: jdbc:mysql://localhost:3306/db_bj_tj?user=root&password=root&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: '@WSX3edc456'
    #password: root
    druid:
      validation-query: SELECT 1
      test-while-idle: true
eureka:
  instance:
    hostname: localhost #eureka 服务的实例名称
    instance-id: payment8001
    prefer-ip-address: true
  client:
    #false 表示不向注册中心注册
    register-with-eureka: true
    #false 表示自己端就是注册中心，我的职责就是维护，并不需要检查
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务需要依赖的这个地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

