## 端口号
server:
  port: 80


## 微服务名
spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  application:
    name: cloud-consumerzk-order
  cloud:
    zookeeper:
      connect-string: 172.16.6.202:2181
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

